/**
 * Generate src/client/features/avatar/avatarWidgets.ts from the vendored widget SVGs
 * (assets/avatar/widgets/**). The SVGs come from Codennnn/vue-color-avatar
 * (MIT, see assets/avatar/UPSTREAM.json); this script inlines them as string
 * literals so the client bundle stays offline-capable with no loader
 * plugins. Re-run after swapping vendored assets:
 *
 *   node scripts/genAvatarWidgets.mjs
 *
 * @module genAvatarWidgets
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const WIDGETS_DIR = join(ROOT, 'assets', 'avatar', 'widgets');
const OUT_FILE = join(ROOT, 'src', 'client', 'features', 'avatar', 'avatarWidgets.ts');

const CATEGORIES = [
  'face',
  'ear',
  'earrings',
  'eyebrows',
  'eyes',
  'nose',
  'glasses',
  'mouth',
  'beard',
  'tops',
  'clothes',
];

/** Read every category/<shape>.svg under the vendored widget tree. */
function collect() {
  const tree = {};
  const hashes = [];
  for (const category of CATEGORIES) {
    const dir = join(WIDGETS_DIR, category);
    const shapes = readdirSync(dir)
      .filter((f) => f.endsWith('.svg'))
      .sort();
    for (const file of shapes) {
      const svg = readFileSync(join(dir, file), 'utf8');
      hashes.push(relative(WIDGETS_DIR, join(category, file)), String(svg.length));
      tree[category] ??= {};
      tree[category][file.replace(/\.svg$/, '')] = svg;
    }
  }
  return { tree, fingerprint: createHash('sha256').update(hashes.join('|')).digest('hex') };
}

const { tree, fingerprint } = collect();

/** JSON string literal is valid TS — stable and escape-correct. */
const lines = CATEGORIES.map((category) => {
  const entries = Object.entries(tree[category]).map(
    ([shape, svg]) => `    ${JSON.stringify(shape)}: ${JSON.stringify(svg)},`,
  );
  return `  ${category}: {\n${entries.join('\n')}\n  },`;
});

const banner = `/**
 * Vendored widget SVG table — GENERATED by scripts/genAvatarWidgets.mjs from
 * assets/avatar/widgets/**. Do not edit by hand; edit the vendored SVGs and
 * re-run the script instead.
 *
 * Widget artwork derives from Codennnn/vue-color-avatar (MIT,
 * Copyright (c) 2021 LeoKu) — provenance in assets/avatar/UPSTREAM.json,
 * license in NOTICE.md.
 *
 * Every entry is a full \`<svg>\` document whose inner content the composer
 * (avatarSvg.ts) splices into a per-widget \`<g>\` layer. \`$fillColor\`
 * placeholders inside the SVG are substituted at render time. Typed as a
 * plain string table (not \`as const\`) so runtime shape ids index freely —
 * unknown ids yield undefined and the composer skips them (forward compat).
 *
 * @module dsh-eteams/client/avatarWidgets
 */

/** category -> shape -> raw SVG document. */
type WidgetSvgTable = { readonly [category: string]: Readonly<Record<string, string>> };

export const AVATAR_WIDGET_SVGS: WidgetSvgTable = {
${lines.join('\n')}
};

/** Fingerprint of the vendored SVG set this table was generated from. */
export const AVATAR_WIDGETS_FINGERPRINT = ${JSON.stringify(fingerprint)};
`;

writeFileSync(OUT_FILE, banner, 'utf8');

const bytes = statSync(OUT_FILE).size;
console.log(
  `avatarWidgets.ts written: ${Object.entries(tree)
    .map(([c, s]) => `${c}=${Object.keys(s).length}`)
    .join(' ')} (${bytes} bytes, ${fingerprint.slice(0, 12)})`,
);
